name: CD

on:
  workflow_dispatch:

jobs:
  CD:
    if: "!contains(github.event.head_commit.message, '[skip cicd]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NTU }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NTU }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Settings Environment Variables 
      env:
        AZs: '${{ vars.AZs }}'
      run: |
        BRANCH="${{ github.ref_name }}"
        ACTOR="${{ github.actor }}"
        
        if [ "$BRANCH" = "main" ]; then
          WORKSPACE="prod"
          BACKEND_KEY="prod_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.PROD_ALLOWED_ORIGIN}}"
        elif [ "$BRANCH" = "dev" ]; then
          WORKSPACE="dev"
          BACKEND_KEY="dev_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.DEV_ALLOWED_ORIGIN}}"
        else
          WORKSPACE="sandbox-${ACTOR}"
          BACKEND_KEY="sandbox_${ACTOR}_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.DEV_ALLOWED_ORIGIN }}"
        fi

        echo "Using Terraform workspace: $WORKSPACE"
        echo "Using Terraform backend key: $BACKEND_KEY"
        echo "using Allowed Origin: $ALLOWED_ORIGIN"
        echo "using Azs: $AZs"

        echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
        echo "BACKEND_KEY=$BACKEND_KEY" >> $GITHUB_ENV
        echo "ALLOWED_ORIGIN=$ALLOWED_ORIGIN" >> $GITHUB_ENV
        echo "AZs=$AZs" >> $GITHUB_ENV


    - name: Terraform Init
      env:
        BACKEND_KEY: ${{ env.BACKEND_KEY }}
      run: |
        echo "Using Terraform backend key: ${{ env.BACKEND_KEY }}"
        terraform init -reconfigure \
            -backend-config="bucket=${{ vars.S3_BUCKET_FOR_TF_STATE_FILE}}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="key=${{ env.BACKEND_KEY }}"
    
    - name: Select or Create Workspace
      run: |
        terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

    - name: Terraform Apply
      run: terraform apply -auto-approve -var "allowed_origin=$ALLOWED_ORIGIN" -var "azs=$AZs"

    - name: Get Terraform Output
      run: |
        echo "bucket_name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
        echo "distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

    - name: Upload website to S3
      run: |
        aws s3 sync website/ s3://$bucket_name --delete --cache-control max-age=300 
    
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id $distribution_id --paths "/*"