name: CI

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
  
jobs:
  Snyk-checks:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-status.outputs.status }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run IaC Snyk Scan
        id: iac
        run: |
          snyk iac test --report --severity-threshold=high --scan=resource-changes
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run App Snyk Scan
        id: app
        run: |
          snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Determine Job Status
        id: set-status
        run: |
          if [ "${{ steps.iac.outcome }}" = "failure" ] || [ "${{ steps.app.outcome }}" = "failure" ]; then
            echo "status=failure" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi

  Terraform-checks:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set-status.outputs.status }}
    needs: snyk-checks
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      env:
        AWS_REGION: $AWS_REGION
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NTU }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NTU }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Settings Environment Variables
      env:
        AZs: '${{ vars.AZs }}'
      run: |
        BRANCH="${{ github.ref_name }}"
        ACTOR="${{ github.actor }}"
        
        if [ "$BRANCH" = "main" ]; then
          WORKSPACE="prod"
          BACKEND_KEY="prod_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.PROD_ALLOWED_ORIGIN}}"
        elif [ "$BRANCH" = "dev" ]; then
          WORKSPACE="dev"
          BACKEND_KEY="dev_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.DEV_ALLOWED_ORIGIN}}"
        else
          WORKSPACE="sandbox-${ACTOR}"
          BACKEND_KEY="sandbox_${ACTOR}_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.DEV_ALLOWED_ORIGIN }}"
        fi
        
        echo "Using Terraform workspace: $WORKSPACE"
        echo "Using Terraform backend key: $BACKEND_KEY"
        echo "using Allowed Origin: $ALLOWED_ORIGIN"
        echo "using Azs: $AZs"

        echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
        echo "BACKEND_KEY=$BACKEND_KEY" >> $GITHUB_ENV
        echo "ALLOWED_ORIGIN=$ALLOWED_ORIGIN" >> $GITHUB_ENV
        echo "AZs=$AZs" >> $GITHUB_ENV

    - name: Terraform fmt
      run: terraform fmt -check
    
    - name: Terraform Init
      env:
        BACKEND_KEY: ${{ env.BACKEND_KEY }}
      run: |
        echo "Using Terraform backend key: ${{ env.BACKEND_KEY }}"
        terraform init -reconfigure \
            -backend-config="bucket=${{ vars.S3_BUCKET_FOR_TF_STATE_FILE}}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="key=${{ env.BACKEND_KEY }}"
    
    - name: Terraform Validate
      run: terraform validate
    
    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
   
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
    
    - name: Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        framework: terraform
        
    - name: Select or Create Workspace
      run: |
        terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

    - name: Terraform Plan
      run: terraform plan -var "allowed_origin=$ALLOWED_ORIGIN" -var "azs=$AZs"
    - name: Determine Terraform Status
      id: set-status
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

  Summary:
    needs: [Snyk-checks, Terraform-checks] # add snyk-checks 
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          SNYK_STATUS=${{ needs.Snyk-checks.outputs.status }}
          TF_STATUS=${{ needs.Terraform-checks.outputs.status }}
          echo '## ðŸš€ Preparing Build Summary ðŸš€' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Snyk-checks     | $SNYK_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform-check       | $TF_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY